name: Auto Api Task

on:
  workflow_dispatch:         # Cho phép chạy thủ công
  schedule:
    - cron: '0 */6 * * *'    # Chạy mỗi 6 tiếng

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt
        pip install PyNaCl

    - name: Run E5 Renew Script
      run: |
        echo "Start at: $(date)"
        python3 auto_renew_e5.py -i $CONFIG_ID -s $CONFIG_KEY -r $CONFIG_REFRESH
      env:
        CONFIG_ID: ${{ secrets.CONFIG_ID }}
        CONFIG_KEY: ${{ secrets.CONFIG_KEY }}
        CONFIG_REFRESH: ${{ secrets.CONFIG_REFRESH }}
